[0m23:31:15.953585 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103c69bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d30b20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d311e0>]}


============================== 23:31:15.957397 | 856c9cde-80b5-4722-adbb-a7904acd3242 ==============================
[0m23:31:15.957397 [info ] [MainThread]: Running with dbt=1.10.13
[0m23:31:15.957708 [debug] [MainThread]: running dbt with arguments {'fail_fast': 'False', 'debug': 'False', 'quiet': 'False', 'profiles_dir': '/Users/sandeep/.dbt', 'write_json': 'True', 'log_cache_events': 'False', 'target_path': 'None', 'log_format': 'default', 'indirect_selection': 'eager', 'use_experimental_parser': 'False', 'send_anonymous_usage_stats': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'partial_parse': 'True', 'invocation_command': 'dbt debug', 'no_print': 'None', 'printer_width': '80', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error': 'None', 'static_parser': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'empty': 'None'}
[0m23:31:15.966295 [info ] [MainThread]: dbt version: 1.10.13
[0m23:31:15.966553 [info ] [MainThread]: python version: 3.10.13
[0m23:31:15.966715 [info ] [MainThread]: python path: /Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/bin/python
[0m23:31:15.966869 [info ] [MainThread]: os info: macOS-14.7.5-arm64-arm-64bit
[0m23:31:16.178304 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.databricks'
[0m23:31:16.178698 [info ] [MainThread]: Using profiles dir at /Users/sandeep/.dbt
[0m23:31:16.178876 [info ] [MainThread]: Using profiles.yml file at /Users/sandeep/.dbt/profiles.yml
[0m23:31:16.179041 [info ] [MainThread]: Using dbt_project.yml file at /Users/sandeep/Downloads/github_repos/dbt_workspaces/demy_dbt/dbt_zoltan/dbt_project.yml
[0m23:31:16.179208 [info ] [MainThread]: Configuration:
[0m23:31:16.179360 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m23:31:16.179513 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m23:31:16.179664 [info ] [MainThread]: Required dependencies:
[0m23:31:16.179844 [debug] [MainThread]: Executing "git --help"
[0m23:31:16.202310 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m23:31:16.202848 [debug] [MainThread]: STDERR: "b''"
[0m23:31:16.203037 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m23:31:16.203224 [info ] [MainThread]: Connection test skipped since no profile was found
[0m23:31:16.203441 [info ] [MainThread]: [31m2 checks failed:[0m
[0m23:31:16.203597 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "ytal_dbt_proj", target "dev" invalid: Runtime Error
    Could not find adapter type databricks!


[0m23:31:16.203757 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/sandeep/Downloads/github_repos/dbt_workspaces/demy_dbt/dbt_zoltan/dbt_project.yml> not found

[0m23:31:16.220438 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.30796167, "process_in_blocks": "0", "process_kernel_time": 0.108015, "process_mem_max_rss": "120750080", "process_out_blocks": "0", "process_user_time": 0.775587}
[0m23:31:16.221149 [debug] [MainThread]: Command `dbt debug` failed at 23:31:16.221077 after 0.31 seconds
[0m23:31:16.221425 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103c69bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d31b70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10594fd00>]}
[0m23:31:16.221683 [debug] [MainThread]: Flushing usage events
[0m23:31:17.390056 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:41:50.357887 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107615bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086dcb20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086dd1e0>]}


============================== 23:41:50.361079 | ebe0879d-585f-4371-a882-eb6e6dae3347 ==============================
[0m23:41:50.361079 [info ] [MainThread]: Running with dbt=1.10.13
[0m23:41:50.361394 [debug] [MainThread]: running dbt with arguments {'quiet': 'False', 'version_check': 'True', 'cache_selected_only': 'False', 'debug': 'False', 'use_colors': 'True', 'no_print': 'None', 'log_path': 'logs', 'warn_error': 'None', 'write_json': 'True', 'invocation_command': 'dbt init dbtlearn', 'indirect_selection': 'eager', 'send_anonymous_usage_stats': 'True', 'target_path': 'None', 'log_cache_events': 'False', 'printer_width': '80', 'partial_parse': 'True', 'fail_fast': 'False', 'introspect': 'True', 'log_format': 'default', 'empty': 'None', 'profiles_dir': '/Users/sandeep/.dbt', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'use_experimental_parser': 'False', 'static_parser': 'True'}
[0m23:41:50.370267 [debug] [MainThread]: Starter project path: /Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/dbt/include/starter_project
[0m23:41:50.373765 [info ] [MainThread]: 
Your new dbt project "dbtlearn" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:41:50.374002 [info ] [MainThread]: Setting up your profile.
[0m23:43:16.388479 [error] [MainThread]: Encountered an error:

[0m23:43:16.399072 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/dbt/cli/requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/dbt/cli/requires.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/dbt/task/init.py", line 113, in generate_target_from_input
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
  File "/Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/click/termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m23:43:16.404659 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 86.08683, "process_in_blocks": "0", "process_kernel_time": 0.15866, "process_mem_max_rss": "112066560", "process_out_blocks": "0", "process_user_time": 0.823132}
[0m23:43:16.408471 [debug] [MainThread]: Command `dbt init` failed at 23:43:16.408175 after 86.09 seconds
[0m23:43:16.410010 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107615bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10925cc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10925d5a0>]}
[0m23:43:16.410998 [debug] [MainThread]: Flushing usage events
[0m23:43:17.493647 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:43:25.510645 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113075b40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11437cb20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11437d1e0>]}


============================== 23:43:25.514205 | 0534875a-4fd1-4ef6-8228-a472ab20fe91 ==============================
[0m23:43:25.514205 [info ] [MainThread]: Running with dbt=1.10.13
[0m23:43:25.514534 [debug] [MainThread]: running dbt with arguments {'cache_selected_only': 'False', 'static_parser': 'True', 'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'debug': 'False', 'no_print': 'None', 'printer_width': '80', 'write_json': 'True', 'use_experimental_parser': 'False', 'target_path': 'None', 'log_cache_events': 'False', 'invocation_command': 'dbt init dbtlearn', 'empty': 'None', 'version_check': 'True', 'quiet': 'False', 'log_format': 'default', 'warn_error': 'None', 'fail_fast': 'False', 'indirect_selection': 'eager', 'log_path': 'logs', 'profiles_dir': '/Users/sandeep/.dbt', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'introspect': 'True'}
[0m23:43:25.526990 [info ] [MainThread]: A project called dbtlearn already exists here.
[0m23:43:25.528356 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.060467836, "process_in_blocks": "0", "process_kernel_time": 0.086655, "process_mem_max_rss": "99876864", "process_out_blocks": "0", "process_user_time": 0.678556}
[0m23:43:25.528761 [debug] [MainThread]: Command `dbt init` succeeded at 23:43:25.528613 after 0.06 seconds
[0m23:43:25.529058 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113075b40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11437d2d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11437dde0>]}
[0m23:43:25.529345 [debug] [MainThread]: Flushing usage events
[0m23:43:27.050348 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:43:53.035737 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104559b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10561cb20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10561d1e0>]}


============================== 23:43:53.039555 | f43362a2-3e09-49fc-a66f-5ed2ba1b2388 ==============================
[0m23:43:53.039555 [info ] [MainThread]: Running with dbt=1.10.13
[0m23:43:53.039897 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'log_format': 'default', 'cache_selected_only': 'False', 'write_json': 'True', 'empty': 'None', 'invocation_command': 'dbt init dbtlearn', 'warn_error': 'None', 'target_path': 'None', 'use_experimental_parser': 'False', 'no_print': 'None', 'send_anonymous_usage_stats': 'True', 'partial_parse': 'True', 'introspect': 'True', 'fail_fast': 'False', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'profiles_dir': '/Users/sandeep/.dbt', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'quiet': 'False', 'indirect_selection': 'eager', 'log_path': 'logs', 'static_parser': 'True', 'log_cache_events': 'False'}
[0m23:43:53.050000 [debug] [MainThread]: Starter project path: /Users/sandeep/.pyenv/versions/3.10.13/envs/venv_dbt_zoltan/lib/python3.10/site-packages/dbt/include/starter_project
[0m23:43:53.053753 [info ] [MainThread]: 
Your new dbt project "dbtlearn" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:43:53.053986 [info ] [MainThread]: Setting up your profile.
[0m23:45:30.749014 [info ] [MainThread]: Profile dbtlearn written to /Users/sandeep/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m23:45:30.772915 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 97.77438, "process_in_blocks": "0", "process_kernel_time": 0.184128, "process_mem_max_rss": "112295936", "process_out_blocks": "0", "process_user_time": 0.793104}
[0m23:45:30.814149 [debug] [MainThread]: Command `dbt init` succeeded at 23:45:30.813658 after 97.82 seconds
[0m23:45:30.815392 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104559b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10561d2d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105447070>]}
[0m23:45:30.816059 [debug] [MainThread]: Flushing usage events
[0m23:45:31.913143 [debug] [MainThread]: An error was encountered while trying to flush usage events
